app_url: "https://testapps.nrs.gov.bc.ca/int/isp/"

reports:

  R10 - Mill Table Audit:

    # Navigate to report
    menu:
      menu_selector: 'role=link[name="Reports"]'
      expanded_selector: 'li.ui-menuitem-active > ul'
    Report:
      report_selector: 'role=link[name="R10 - Mill Table Audit"]'

    inputs:

      mills_dropdown:
        type: checkbox_dropdown
        selector: 'label:has-text("Mill") >> .. >> .ui-selectcheckboxmenu-trigger'
        values: []
      zones_dropdown:
        type: checkbox_dropdown
        selector: 'label:has-text("Zone") >> .. >> .ui-selectcheckboxmenu-trigger'
 #       select_all: true
        values:
          - "5 - Northern Interior"
          - "6 - Skeena"
          - "7 - Southern Interior"          
          - "8 - Southern Cariboo"
          - "9 - Fort Nelson - Peace"
      start_month:
        type: dropdown
        selector: "[id='form:selectFromMonth'] button"
        value: "JAN"
      start_year:
        type: input
        selector: "[id='form:selectFromYear']"
        value: "2017"
      end_month:
        type: dropdown
        selector: "[id='form:selectToMonth'] button"
        value: "MAR"
      end_year:
        type: input
        selector: "[id='form:selectToYear']"
        value: "2026"
    download_button: 'role=button[name="PDF"]'

  R11 - Lumber-chip Summary:

    # Navigate to report
    menu:
      menu_selector: 'role=link[name="Reports"]'
      expanded_selector: 'li.ui-menuitem-active > ul'
    Report:
      report_selector: 'role=link[name="R11 - Lumber/Chip Summary"]'

    inputs:

      leading_toggle:
        type: checkbox
        selector: '[id="form:j_idt50"]'
        value: true
      mills_dropdown:
        type: checkbox_dropdown
        selector: 'label:has-text("Mill") >> .. >> .ui-selectcheckboxmenu-trigger'
        values: []
      zones_dropdown:
        type: checkbox_dropdown
        selector: 'label:has-text("Zone") >> .. >> .ui-selectcheckboxmenu-trigger'
        values:
          - "5 - Northern Interior"
          - "6 - Skeena"
          - "7 - Southern Interior"          
          - "8 - Southern Cariboo"
          - "9 - Fort Nelson - Peace"
      start_month:
        type: dropdown
        selector: "[id='form:selectFromMonth'] button"
        value: "JAN"
      start_year:
        type: input
        selector: "[id='form:selectFromYear']"
        value: "2017"
      end_month:
        type: dropdown
        selector: "[id='form:selectToMonth'] button"
        value: "MAR"
      end_year:
        type: input
        selector: "[id='form:selectToYear']"
        value: "2026"
      detail_mode:
        type: checkbox
        selector: '[id="form:j_idt83"]'
        value: true
    download_button: 'role=button[name="PDF"]'

  R12 - Sales Summary Audit:

    # Navigate to report
    menu:
      menu_selector: 'role=link[name="Reports"]'
      expanded_selector: 'li.ui-menuitem-active > ul'
    Report:
      report_selector: 'role=link[name="R12 - Sales Summary Audit"]'

    inputs:

      mills_dropdown:
        type: checkbox_dropdown
        selector: 'label:has-text("Mill") >> .. >> .ui-selectcheckboxmenu-trigger'
        values: []
      zones_dropdown:
        type: checkbox_dropdown
        selector: 'label:has-text("Zone") >> .. >> .ui-selectcheckboxmenu-trigger'
        values:
          - "5 - Northern Interior"
          - "6 - Skeena"
          - "7 - Southern Interior"          
          - "8 - Southern Cariboo"
          - "9 - Fort Nelson - Peace"
      start_month:
        type: dropdown
        selector: "[id='form:selectFromMonth'] button"
        value: "JAN"
      start_year:
        type: input
        selector: "[id='form:selectFromYear']"
        value: "2017"
      end_month:
        type: dropdown
        selector: "[id='form:selectToMonth'] button"
        value: "MAR"
      end_year:
        type: input
        selector: "[id='form:selectToYear']"
        value: "2026"
      detail_mode:
        type: checkbox
        selector: '[id="form:j_idt69"]'
        value: true
    download_button: 'role=button[name="PDF"]'


  R13 - Ad Hoc:

    # Navigate to report
    menu:
      menu_selector: 'role=link[name="Reports"]'
      expanded_selector: 'li.ui-menuitem-active > ul'
    Report:
      report_selector: 'role=link[name="R13 - Ad Hoc"]'

    inputs:

      Report_Name:
        type: input
        selector: "[id='form:j_idt47']"
        value: "Test Report"
      mills_Number_dropdown:
        type: checkbox_dropdown
        selector: 'label:has-text(" Mill Number(s)") >> .. >> .ui-selectcheckboxmenu-trigger'
        values: []
      mills_Name_dropdown:
        type: checkbox_dropdown
        selector: 'label:has-text(" Mill Names(s)") >> .. >> .ui-selectcheckboxmenu-trigger'
        values: []
      zones_dropdown:
        type: checkbox_dropdown
        selector: 'label:has-text("Zone") >> .. >> .ui-selectcheckboxmenu-trigger'
        values:
          - "5 - Northern Interior"
          - "6 - Skeena"
          - "7 - Southern Interior"          
          - "8 - Southern Cariboo"
          - "9 - Fort Nelson - Peace"
      Summary_Report_Type:
        type: checkbox
        selector: '[id="form:reportType"] ul > li:has-text("Regular Chip")'
      zones_dropdown:
        type: checkbox_dropdown
        selector: 'label:has-text("Chip Species") >> .. >> .ui-selectcheckboxmenu-trigger'
        values:
          - "CE - Cedar"
          - "DC - Deciduous sold as Chips"
          - "WW - Whitewood sold as Chips"          
      start_month:
        type: dropdown
        selector: "[id='form:selectFromMonth'] button"
        value: "JAN"
      start_year:
        type: input
        selector: "[id='form:selectFromYear']"
        value: "2017"
      end_month:
        type: dropdown
        selector: "[id='form:selectToMonth'] button"
        value: "MAR"
      end_year:
        type: input
        selector: "[id='form:selectToYear']"
        value: "2026"
      Original Volume:
        type: checkbox
        selector: '[id="form:j_idt128"]'
        value: true
      Converted Volume:
        type: checkbox
        selector: '[id="form:j_idt131"]'
        value: true
      Amount:
        type: checkbox
        selector: '[id="form:j_idt134"]'
        value: true
      AMV:
        type: checkbox
        selector: '[id="form:j_idt137"]'
        value: true
      Size:
        type: checkbox
        selector: '[id="form:j_idt140"]'
        value: true
      Width:
        type: checkbox
        selector: '[id="form:j_idt143"]'
        value: true
      Thickness:
        type: checkbox
        selector: '[id="form:j_idt146"]'
        value: true
      Unit of Measure:
        type: checkbox
        selector: '[id="form:j_idt152"]'
        value: true
    download_button: 'role=button[name="PDF"]'